name: Build Blender Extension
description: Action to automatically build the Blender Extension and store the resulting .zip artifact.
author: DShot92, Daniele Stochino

branding:
  icon: box
  color: blue

runs:
  using: composite

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install required Python packages
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests toml-cli toml beautifulsoup4

    - name: Run get_latest_blender.py and capture output
      shell: bash
      id: get_blender_url
      run: |
        mkdir -p $HOME/scripts
        wget -O $HOME/scripts/get_latest_blender.py https://raw.githubusercontent.com/dshot92/build-blender-extension/main/get_latest_blender.py
        echo "BLENDER_URL=$( python $HOME/scripts/get_latest_blender.py)" >> $GITHUB_ENV

    - name: Download and extract Blender
      shell: bash
      run: |
        wget -O /home/runner/blender.tar.xz "${{ env.BLENDER_URL }}"
        mkdir -p /home/runner/.local/bin /home/runner/blender
        tar -xf /home/runner/blender.tar.xz -C /home/runner/blender --strip-components=1
        ln -s /home/runner/blender/blender /home/runner/.local/bin/blender

    - name: Extract version from blender_manifest.toml
      shell: bash
      id: extract_version
      run: |
        echo "EXT_VERSION=$(python -c "import toml; print(toml.load('./blender_manifest.toml')['version'])")" >> $GITHUB_ENV
        echo "ZIP_FILE_PATH=/home/runner/${{ github.event.repository.name }}-${{ env.EXT_VERSION }}.zip" >> $GITHUB_ENV  # Store zip file path in environment variable

    - name: Build extension and capture zip filename
      shell: bash
      run: |
        blender --command extension build --output-filepath="${{ env.ZIP_FILE_PATH }}"

    - name: Validate extension
      shell: bash
      run: |
        blender --command extension validate "${{ env.ZIP_FILE_PATH }}"

    - name: Unzip the file
      shell: bash
      run: |
        unzip "${{ env.ZIP_FILE_PATH }}" -d "/home/runner/${{ github.event.repository.name }}-${{ env.EXT_VERSION }}"

    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}-${{ env.EXT_VERSION }}
        path: /home/runner/${{ github.event.repository.name }}-${{ env.EXT_VERSION }}

