name: 'Build Blender Extension'
description: 'Action to automatically build the Blender Extension and store the resulting .zip artifact.'
author: 'DShot92, Daniele Stochino'

branding:
  icon: 'box'
  color: 'blue'

runs:
  using: 'composite'

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install required Python packages
      shell: bash
      run: pip install requests toml-cli toml beautifulsoup4

    - name: Get latest daily Blender build URL
      shell: bash
      run: python .github/workflows/get_latest_blender.py > blender_url.txt

    - name: Download and extract Blender
      shell: bash
      run: |
        wget -O /home/runner/blender.tar.xz $(cat blender_url.txt)
        mkdir -p /home/runner/.local/bin /home/runner/blender
        tar -xf /home/runner/blender.tar.xz -C /home/runner/blender --strip-components=1
        ln -s /home/runner/blender/blender /home/runner/.local/bin/blender
    
    - name: remove blender_url.txt
      shell: bash
      run: rm blender_url.txt

    - name: Extract version from blender_manifest.toml
      shell: bash
      id: extract_version
      run: |
        version=$(python -c "import toml; print(toml.load('./blender_manifest.toml')['version'])")
        echo "Version: $version"
        echo "version=$version" >> $GITHUB_ENV  # Store version in environment variable
        echo "ZIP_FILE_PATH=/home/runner/${{ github.event.repository.name }}-${version}.zip" >> $GITHUB_ENV  # Store zip file path in environment variable

    - name: Build extension and capture zip filename
      shell: bash
      run: |
        blender --command extension build --output-filepath=${{ env.ZIP_FILE_PATH }}

    - name: Unzip the file
      shell: bash
      run: |
        unzip ${{ env.ZIP_FILE_PATH }} -d /home/runner/${{ github.event.repository.name }}-${{ env.version }}

    - name: Archive artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}-${{ env.version }}
        path: /home/runner/${{ github.event.repository.name }}-${{ env.version }}
